title: "Lanyiwè TONGO - Statistique & Données"
email: lanyiwetongo@gmail.com
description: >-
  Plateforme dédiée à la statistique et à la science des données. Animée par Lanyiwè TONGO.
baseurl: "" # le site est à la racine
url: "https://lanyiwetongo.github.io"

linkedin_username: lanyiwetongo
linkedin_url: "https://www.linkedin.com/in/lanyiwetongo"
github_username: lanyiwe

# Build settings
theme: minima
plugins:
  - jekyll-feed


header_pages:
  - index.markdown
  - about.md
  - Publications.md
disqus:
  shortname: lanyiwetongo-Publications
